name: Get cat
on: workflow_dispatch
    
jobs:
  get-cat:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“ Get code
        uses: actions/checkout@v4

      - name: ðŸ˜º Get cat fact
        id: get-cat
        uses: ./.github/actions/get-cat
        with:
          url: 'https://catfact.ninja/fact'

      - name: ðŸ–¨ï¸ Print cat fact
        run: |
          echo ${{ steps.get-cat.outputs.fact }}
          echo "ðŸ˜º Cat fact: ${{ steps.get-cat.outputs.fact }}" >> $GITHUB_STEP_SUMMARY

      - name: ðŸðŸ˜º Get cat fact with Python
        id: get-cat-python
        uses: ./.github/actions/get-python-cat
        with:
          url: 'https://catfact.ninja/fact'

      - name: ðŸ–¨ï¸ Print cat fact
        run: |
          echo ${{ steps.get-cat.outputs.fact }}
          echo "ðŸ˜º Cat fact: ${{ steps.get-cat.outputs.fact }}" >> $GITHUB_STEP_SUMMARY