name: Get cat
on: workflow_dispatch
    
jobs:
  get-cat:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“ Get code
        uses: actions/checkout@v3

      - name: ğŸ˜º Get cat fact
        id: get-cat
        uses: ./.github/actions/get-cat

